### PR TITLE
chore(deps): upgrade latest

### PR DESCRIPTION
**Pull request by TheAlmightyCrumb**

### CODE REVIEW

**Review by shakederin — APPROVED** [review]
Everything works?
I notice a major

**Comment by TheAlmightyCrumb** [comment]
> Everything works? I notice a major

Yup, the build works fine.

**Comment by shakederin** [comment]
> > Everything works? I notice a major
> 
> Yup, the build works fine.

Did you open it on Codux?

**Comment by TheAlmightyCrumb** [comment]
> > > Everything works? I notice a major
> > 
> > 
> > Yup, the build works fine.
> 
> Did you open it on Codux?

Of course. It is an update to the vite svgr plugin which allows the following syntax:
```
import { ReactComponent as MyLogo } from './assets/my-logo.svg';
```
In codux all the boards work, but still, if it had any damaging effect - we should see it when running the build.

**Pull request merged**
